package ufal.auth;

public enum Action {
  SIGNUP_USER, LOGIN_USER, DOES_USER_EXIST, ALTERAR_DADOS_CADASTRAIS, LISTAR_USUARIOS, BUSCAR_USUARIO,
  IS_CLIENTE, CRIAR_SERVICO, BUSCAR_SERVICO, LISTAR_SERVICOS, ATUALIZAR_SERVICO, EXCLUIR_SERVICO, CRIAR_PLANO,
  BUSCAR_PLANO, ATUALIZAR_PLANO, EXCLUIR_PLANO, ASSINAR_PLANO, LISTAR_SERVICOS_DISPONIVEIS, CANCELAR_ASSINATURA
}
